### ISSUE TITLE
Missing Java 8 support

### ISSUE THREAD

**Issue by florian-douay** [icescrum/iceScrum#30] opened 2016-05-22 10:57 UTC
Java 7 starts to be really deprecated

http://www.java.com/en/download/faq/java_7.xml

Furthermore, the standalone version might be hosted on a machine with other tools like Jenkins. 
For example, unit test execution has to run with Java 8 when the product is developed with Java 8 features.

Should Java 8 support be one of top priorities ?

**Comment by noullet** [comment] 2016-05-23 07:53
Hello Florian,

Thanks for your comment.

You are right, Java 8 support has a very high priority. The problem is that the dependencies of iceScrum R6 prevent Java 8 support. 

We are currently developing a new version if iceScrum under the name "iceScrum R7". In addition to a brand new UI, this version has updated dependencies that enables Java 8 and Tomcat 8 support. This version will be available in public beta this week.

**Comment by florian-douay** [comment] 2016-05-31 19:31
Thank you for your involvement. We're really waiting for this R7.

When available, how will we get it ? On official web site ? Releases ? Dedicated branch ? Something else ?

**Comment by noullet** [comment] 2016-06-01 13:42
iceScrum R7 will be available through this website just as before. At first it will be released this week only as a hosted version so people can learn to use it and provide feedback before the general availability. 

In the meantime, the community source code keeps being available on this repository and iceScrum R7 is developed on the master branch.

**Comment by vbarrier** [comment] 2017-08-29 18:55
V7 is now the default version of IceScrum and support java 8 :)

**Closed by vbarrier** 2017-08-29 18:55 UTC
